import type { NextConfig } from 'next';

/*
 * The live rooms embed a meeting. A page-level `camera=()` also turns the
 * camera off for every iframe inside the page, so the site-wide policy below
 * would silence a real call. These routes allow camera, microphone and screen
 * share to this origin and the meeting provider, and to nobody else.
 */
const MEETING = 'self "https://zoom.us" "https://*.zoom.us"';
const LIVE_PERMISSIONS = `camera=(${MEETING}), microphone=(${MEETING}), display-capture=(${MEETING}), geolocation=(self), payment=(self)`;

const nextConfig: NextConfig = {
  /**
   * Cache Components (Next.js 16's Partial Prerendering model).
   *
   * This is the architectural backbone of the storefront:
   *   - catalogue reads are wrapped in `use cache` + `cacheTag`, so product,
   *     category and brand pages ship a complete static shell from the CDN;
   *   - anything session-shaped (bag, wishlist, account, seller/admin consoles)
   *     sits behind `<Suspense>` and streams at request time;
   *   - Server Actions call `updateTag` for read-your-writes and
   *     `revalidateTag(tag, 'max')` for eventually-consistent catalogue updates.
   *
   * The practical effect for shoppers: a product page's copy, price and imagery
   * are prerendered HTML, while "in your bag" and live stock stream in.
   */
  cacheComponents: true,

  /*
   * `typedRoutes` is deliberately OFF.
   *
   * It validates `href` against the generated route union, which only accepts
   * string LITERALS. Almost every link in this app is composed at runtime — a
   * slug read from Mongo, or a filter URL built by `lib/product-query` — and
   * those arrive as `string`, which the union rejects no matter how correct the
   * value is. Enabling it would mean casting at every call site, and a cast on
   * every href is not type safety, it is the appearance of it.
   *
   * Route correctness is instead guaranteed where the values actually come
   * from: slug lookups check `slug` and `slugHistory` and call `notFound()`
   * when neither matches.
   */
  typedRoutes: false,

  reactStrictMode: true,

  // Nothing is gained by announcing the framework to every scanner.
  poweredByHeader: false,

  images: {
    /**
     * Product imagery is generated by our own media route as SVG. Allowing SVG
     * through the optimiser is only safe because the source is first-party and
     * the sandbox CSP below neutralises scripting inside the file.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    formats: ['image/avif', 'image/webp'],
    // 3:4 portrait product tiles plus the usual layout widths.
    deviceSizes: [360, 420, 640, 750, 828, 1080, 1200, 1440, 1920, 2048],
    imageSizes: [32, 48, 64, 96, 128, 160, 200, 256, 384],
    qualities: [60, 75, 90],
    minimumCacheTTL: 14400,
    /*
     * Every <Image> resolves through this loader, which is what makes "images
     * are served by ImageKit" true of the whole app rather than of the handful
     * of components someone remembered to change. With no ImageKit credentials
     * it hands the request back to `/_next/image`, so a clone still runs.
     */
    loaderFile: './src/lib/image-loader.ts',
    remotePatterns: [
      // Seller-uploaded media would land on the asset CDN in production.
      { protocol: 'https', hostname: 'cdn.vestrawab.example' },
      /*
       * Representative product photography for the demo dataset. See
       * `server/seed/photos.ts` — these stand in for seller uploads and are
       * replaced by them before launch. `MEDIA_SOURCE=generated` drops this
       * dependency entirely and falls back to the first-party SVG renderer.
       */
      { protocol: 'https', hostname: 'images.unsplash.com' },
      // ImageKit's delivery host, when configured.
      { protocol: 'https', hostname: 'ik.imagekit.io' },
    ],
  },

  experimental: {
    optimizePackageImports: ['lucide-react', 'recharts'],
    /*
     * Required for `forbidden()` and `unauthorized()` to render the
     * `forbidden.tsx` / `unauthorized.tsx` boundaries. Without it those calls
     * are inert and `requirePermission` silently lets everyone through — the
     * RBAC smoke test caught exactly that: a Support user could open the
     * finance ledger.
     */
    authInterrupts: true,
  },

  /**
   * Baseline security headers. In production these belong at the edge too, but
   * shipping them from the app guarantees they are never silently lost.
   */
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=(self), payment=(self)',
          },
          { key: 'X-DNS-Prefetch-Control', value: 'on' },
          /*
           * A baseline policy that restricts nothing the app loads, only what
           * it never needs: plugins, a rewritten <base>, being framed by other
           * sites and forms posting off-site. A full script policy needs
           * per-request nonces, which would make every prerendered page dynamic.
           */
          {
            key: 'Content-Security-Policy',
            value: "object-src 'none'; base-uri 'self'; frame-ancestors 'self'; form-action 'self'",
          },
          ...(process.env.NODE_ENV === 'production'
            ? [{ key: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains' }]
            : []),
        ],
      },
      // Later entries win for the same key, so these override the camera ban.
      { source: '/live/:path*', headers: [{ key: 'Permissions-Policy', value: LIVE_PERMISSIONS }] },
      {
        source: '/seller/live/:path*',
        headers: [{ key: 'Permissions-Policy', value: LIVE_PERMISSIONS }],
      },
      {
        // Generated product imagery is immutable for a given spec string.
        source: '/api/media/:path*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
    ];
  },

  /**
   * Legacy/vanity URL shape kept alive so inbound links and old sitemaps do not
   * 404. Slug history redirects are handled dynamically in `proxy.ts`.
   */
  async redirects() {
    return [
      { source: '/cart', destination: '/bag', permanent: true },
      { source: '/products/:slug', destination: '/product/:slug', permanent: true },
      { source: '/shop/:slug', destination: '/category/:slug', permanent: true },
    ];
  },
};

export default nextConfig;
