import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  /**
   * Cache Components (Next.js 16's Partial Prerendering model).
   *
   * This is the architectural backbone of the storefront:
   *   - catalogue reads are wrapped in `use cache` + `cacheTag`, so product,
   *     category and brand pages ship a complete static shell from the CDN;
   *   - anything session-shaped (bag, wishlist, account, seller/admin consoles)
   *     sits behind `<Suspense>` and streams at request time;
   *   - Server Actions call `updateTag` for read-your-writes and
   *     `revalidateTag(tag, 'max')` for eventually-consistent catalogue updates.
   *
   * The practical effect for shoppers: a product page's copy, price and imagery
   * are prerendered HTML, while "in your bag" and live stock stream in.
   */
  cacheComponents: true,

  /*
   * `typedRoutes` is deliberately OFF.
   *
   * It validates `href` against the generated route union, which only accepts
   * string LITERALS. Almost every link in this app is composed at runtime — a
   * slug read from Mongo, or a filter URL built by `lib/product-query` — and
   * those arrive as `string`, which the union rejects no matter how correct the
   * value is. Enabling it would mean casting at every call site, and a cast on
   * every href is not type safety, it is the appearance of it.
   *
   * Route correctness is instead guaranteed where the values actually come
   * from: slug lookups check `slug` and `slugHistory` and call `notFound()`
   * when neither matches.
   */
  typedRoutes: false,

  reactStrictMode: true,

  images: {
    /**
     * Product imagery is generated by our own media route as SVG. Allowing SVG
     * through the optimiser is only safe because the source is first-party and
     * the sandbox CSP below neutralises scripting inside the file.
     */
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    formats: ['image/avif', 'image/webp'],
    // 3:4 portrait product tiles plus the usual layout widths.
    deviceSizes: [360, 420, 640, 750, 828, 1080, 1200, 1440, 1920, 2048],
    imageSizes: [32, 48, 64, 96, 128, 160, 200, 256, 384],
    qualities: [60, 75, 90],
    minimumCacheTTL: 14400,
    remotePatterns: [
      // Seller-uploaded media would land on the asset CDN in production.
      { protocol: 'https', hostname: 'cdn.vestra.example' },
    ],
  },

  experimental: {
    optimizePackageImports: ['lucide-react', 'recharts'],
  },

  /**
   * Baseline security headers. In production these belong at the edge too, but
   * shipping them from the app guarantees they are never silently lost.
   */
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=(self), payment=(self)',
          },
          { key: 'X-DNS-Prefetch-Control', value: 'on' },
        ],
      },
      {
        // Generated product imagery is immutable for a given spec string.
        source: '/api/media/:path*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
    ];
  },

  /**
   * Legacy/vanity URL shape kept alive so inbound links and old sitemaps do not
   * 404. Slug history redirects are handled dynamically in `proxy.ts`.
   */
  async redirects() {
    return [
      { source: '/cart', destination: '/bag', permanent: true },
      { source: '/products/:slug', destination: '/product/:slug', permanent: true },
      { source: '/shop/:slug', destination: '/category/:slug', permanent: true },
    ];
  },
};

export default nextConfig;
