import 'server-only';

import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { imageKitReady } from '@/config/imagekit';

import { SIGNATURES, inspect } from './signatures';
import type { MediaStore } from './types';

export type { MediaStore, StoredMedia, UploadResult } from './types';

/**
 * Media storage.
 *
 * Seller uploads need somewhere to live. In production that is ImageKit, which
 * stores the original and serves every derivative from its CDN; with no
 * ImageKit credentials configured it is the local disk, behind the same
 * interface — so a clone of this repository runs with no accounts to create,
 * and moving between the two is a configuration change rather than a code one.
 *
 * What neither driver does is trust the browser. A file's declared `type` and
 * its extension are both attacker-controlled, so `signatures.ts` checks the
 * actual bytes, and both drivers go through it.
 */

/* ------------------------------------------------------------ disk driver */

const UPLOAD_DIR = path.join(/*turbopackIgnore: true*/ process.cwd(), process.env.DATA_DIR || '.data', 'uploads');

export function diskMediaStore(): MediaStore {
  return {
    name: 'disk',

    async put(file, { scope }) {
      const inspected = await inspect(file);
      if (!inspected.ok) return inspected;

      // Vercel's disk is read-only and not shared between instances: a file
      // written here would vanish, so refuse clearly instead of failing on mkdir.
      if (process.env.VERCEL) {
        return { ok: false, error: 'Uploads need ImageKit on this host. Set the three ImageKit variables.' };
      }

      // Content-addressed, so re-uploading the same photo does not duplicate it.
      const digest = createHash('sha256').update(inspected.bytes).digest('hex').slice(0, 20);
      const id = `${scope}-${digest}-${randomUUID().slice(0, 8)}.${inspected.signature.extension}`;

      await mkdir(UPLOAD_DIR, { recursive: true });
      await writeFile(path.join(UPLOAD_DIR, id), inspected.bytes);

      return {
        ok: true,
        media: {
          id,
          url: `/api/media/upload/${id}`,
          contentType: inspected.signature.contentType,
          bytes: inspected.bytes.byteLength,
          width: inspected.width,
          height: inspected.height,
        },
      };
    },

    async get(id) {
      // Ids are generated by `put` and never contain a separator, so a
      // traversal attempt cannot escape the upload directory.
      if (!/^[A-Za-z0-9._-]+$/.test(id) || id.includes('..')) return null;

      const signature = SIGNATURES.find((s) => id.endsWith(`.${s.extension}`));
      if (!signature) return null;

      try {
        const body = await readFile(path.join(UPLOAD_DIR, id));
        return { body, contentType: signature.contentType };
      } catch {
        return null;
      }
    },

    async remove(id) {
      if (!/^[A-Za-z0-9._-]+$/.test(id) || id.includes('..')) return;
      try {
        await unlink(path.join(UPLOAD_DIR, id));
      } catch {
        // Already gone is the desired end state.
      }
    },
  };
}

/* ---------------------------------------------------------------- selection */

let store: MediaStore | null = null;

/**
 * The active store.
 *
 * Resolved once per process. Deliberately NOT re-read per call: a half-loaded
 * environment that flipped drivers between two uploads in the same request
 * would put one product's photographs in two places.
 */
export function mediaStore(): MediaStore {
  if (!store) {
    store = imageKitReady() ? lazyImageKitStore() : diskMediaStore();
  }
  return store;
}

/**
 * The ImageKit driver, loaded on demand.
 *
 * `require` at module scope would pull ImageKit's config into every build that
 * never uses it. This keeps the import inside the call while still presenting a
 * synchronous `MediaStore` to callers.
 */
function lazyImageKitStore(): MediaStore {
  let real: MediaStore | null = null;
  const load = async (): Promise<MediaStore> => {
    if (!real) {
      const { imageKitMediaStore } = await import('./imagekit');
      real = imageKitMediaStore();
    }
    return real;
  };

  return {
    name: 'imagekit',
    put: async (file, options) => (await load()).put(file, options),
    get: async (id) => (await load()).get(id),
    remove: async (id) => (await load()).remove(id),
  };
}
